{"uuid": "4efec8af-7d2c-4e66-a0e6-fdb93748ba66", "children": ["c3c1bb17-3614-4038-aa60-5e5762b5f35b"], "befores": [{"name": "screenshot_on_failure", "status": "passed", "start": 1597851191474, "stop": 1597851191474}], "afters": [{"name": "screenshot_on_failure::fin", "status": "broken", "statusDetails": {"message": "TypeError: 'WebDriver' object is not callable\n", "trace": "  File \"c:\\users\\m.kononova\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\m.kononova\\environments\\flexite_autotests\\conftest.py\", line 43, in fin\n    driver = browser()\n"}, "start": 1597851195771, "stop": 1597851195772}], "start": 1597851191474, "stop": 1597851195772}